version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=INFO
      - BASE_URL=http://localhost:8080
      - DATABASE_URL=postgres://gopher:12345@postgres:5432/shortener
    ports:
      - 8080:8080

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
